### ISSUE TITLE
Downsample Not Saved

### ISSUE THREAD

**Issue by william-silversmith** [StructuralNeurobiologyLab/SyConn#29]
Hi! Just wanted to point out that the PrecomputedSkeleton.downsample function is performed on a copy. You need to write ` skels[ii] = skels[ii].downsample(10)` for it to have an effect.

https://github.com/StructuralNeurobiologyLab/SyConn/blob/c471a69d94a9ef1b0435e5e37036ca31810a4aaf/syconn/proc/skeleton.py#L73

**Comment by pschubert** [comment]
Hi William, thanks for noticing! That reminds me that I need to merge our development branch to the master as soon as possible. Here is what we do currently:
https://gitlab.mpcdf.mpg.de/pschuber/SyConn/-/blob/ptconv/syconn/proc/skeleton.py#L79

I will close this issue once I pushed the changes to the master.

**Comment by pschubert** [comment]
fixed in commit https://github.com/StructuralNeurobiologyLab/SyConn/commit/e2803341a56a8f1bcd56091b16e0cf5d2a454ca7 .
