### ISSUE TITLE
SyConn elektronn example fails with fatal error

### ISSUE THREAD

**Issue by rasaxena** [StructuralNeurobiologyLab/SyConn#3]
Under the latest arch and Ubuntu 16.04 LTS, the elektronn inference crashes in CPU mode (possibly also GPU, not tested). Fatal Python error: PyEval_SaveThread: NULL tstate

**Comment by sdorkenw** [comment]
Thanks for creating this issue. Could you share the command you ran and which CNN you used? 

The elektronn inference is only used in `join_chunky_inference` from `predictor_cnn.py` (l. 334). Hence, I expect you used this function. There, the inference functionality itself is provided by `ElektroNN`. `SyConn` only combines this with chunkdatasets from `knossos_utils`. The problem could now arise from `chunky` (`knossos_utils`), this small part of `SyConn` or `ElektroNN`.

**Comment by pschubert** [comment]
This issue is outdated as SyConn has meanwhile been refactored to use elektronn3 (https://github.com/ELEKTRONN/elektronn3).
