### ISSUE TITLE
Provided data files: not available now

### ISSUE THREAD

**Issue by JackieZhai** [StructuralNeurobiologyLab/SyConn#30]
Those two zip files:
"SyConnDenseCube.zip"(http://brainpuzzler.org/downloads/SyConnDenseCube.zip)
and
"gt_syconn_bird_sj_vc_mi.zip"(http://brainpuzzler.org/downloads/gt_syconn_bird_sj_vc_mi.zip)
on the website "http://structuralneurobiologylab.github.io/SyConn"
have been expired / not available.

Could you please renew the file links?

Many thanks!

**Comment by JackieZhai** [comment]
@sdorkenw @pschubert

**Comment by jmrk84** [comment]
Dear Jackie -- Thanks for pointing this out. We found the issue, the links will be updated asap.

**Comment by jmrk84** [comment]
Dear Jackie, here are the new links:

**Comment by JackieZhai** [comment]
Thank you for the response!
