### ISSUE TITLE
Better cluster job management

### ISSUE THREAD

**Issue by jmrk84** [StructuralNeurobiologyLab/SyConn#8]
- Add automatic resubmission of failed jobs
- Report permanently failing jobs (limit retries)

**Comment by pschubert** [comment]
This has been added in #9. In the current implementation #21 `QSUB_script` has a keyword argument for setting a maximum number of retries (`max_iterations`). A `RuntimeError` will be raised if the number of attempts exceeded this value or if all submitted jobs failed.
